app/urls.py
from django.urls import path
from .views import addQuestion, delete_user, index, login_request, logout_request, register_request, provinsi, berita, profile, setting, change_password, delete_user, rumahsakit

urlpatterns = [
    path('', index, name='index'),
    path('login/', login_request, name='login'),
    path('register/', register_request, name='register'),
    path('logout/', logout_request, name='logout'),
    path('provinsi/', provinsi, name='provinsi'),
    path('berita/', berita, name='berita'),
    path('profil/', profile, name='profil'),
    path('setting/', setting, name='setting'),
    path('password/', change_password, name='password'),
    path('add-question/', addQuestion, name='add-question'),
    path('delete-user/', delete_user, name='delete-user'),
    path('rumahsakit/', rumahsakit, name='rumahsakit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
import app.urls as app
import forum.urls as forum
from django.conf.urls.static import static
from django.conf import settings
handler404 = 'app.views.error_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(app)),
    path('', include(forum))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(
        User, null=True, blank=True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    gender = models.CharField(max_length=200, null=True)
    number_phone = models.CharField(max_length=200, null=True)
    bio = models.CharField(max_length=200, null=True)
    province = models.CharField(max_length=200, null=True)
    date_of_birth = models.DateField(null=True)
    profile_pic = models.ImageField(
        default="undraw_profile.svg", upload_to='users/', null=True, blank=True)

    def __str__(self):
        return f'{self.user.username}-Profile'


class Question(models.Model):
    username = models.CharField(max_length=100)
    question = models.TextField()
    date = models.DateTimeField(auto_now_add=True, blank=True)

app/templates/base_site.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{title}}</title>

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- website icon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/icon.png' %}" />

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/media-query.css' %}">

    <!-- Custom styles for this page -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar shadow mb-4 p-3">
                    <i id="toggle" class="fas fa-bars ml-2"></i>
                      <div id="links-desktop">
                        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                          <li class="nav-item active">
                            <a class="nav-link font-weight-bold" style="color: #5f5b5b;" href="/">Dashboard</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link font-weight-bold" style="color: #5f5b5b;" href="/rumahsakit">Rumah Sakit</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link font-weight-bold" style="color: #5f5b5b;" href="/berita">Berita</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link font-weight-bold" style="color: #5f5b5b;" href="/forum">Forum</a>
                          </li>
                        </ul>
                      </div>
                      
                      <div id="links-mobile">
                        <ul class="navbar-nav mr-auto mt-lg-0">
                          <li class="nav-item active">
                            <a class="nav-link font-weight-bold" style="color: #5f5b5b;" href="/">Dashboard</a>
                          </li>
                          <li class="nav-item active">
                            <a class="nav-link font-weight-bold" style="color: #5f5b5b;" href="/">Rumah Sakit</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link font-weight-bold" style="color: #5f5b5b;" href="/berita">Berita</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link font-weight-bold" style="color: #5f5b5b;" href="/forum">Forum</a>
                          </li>
                          <i id="close" class="fas fa-times"></i>
                        </ul>
                      </div>
                      

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        {% if user.is_authenticated %}
                        <!-- Button trigger modal -->
                        <div class="d-flex align-items-center">
                            <!-- Desktop -->
                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#questionModal" id="desktop-question">
                            <i class="far fa-question-circle mr-1"></i>Punya Pertanyaan?
                          </button>
                          <!-- Mobile -->
                          <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#questionModal" id="mobile-question">
                            <i class="far fa-question-circle"></i>
                          </button>
                        </div>

                        <!-- Modal -->
                        <div class="modal fade" id="questionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="modal-title text-dark" id="exampleModalLabel">Punya Pertanyaan?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                                <div class="modal-body">
                                <form action="/add-question/" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="hidden" value="{{username}}" name="username">
                                        <label for="questionArea" class="text-dark mb-2">Tulis pertanyaan di kolom berikut. Kami akan berusaha menjawabnya melalui forum.</label>
                                        <textarea class="form-control" name="question" id="questionArea" rows="6"></textarea>
                                    </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-info">Kirim</button>
                                    </div>
                                </form>
                            </div>
                            </div>
                        </div>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information --> 
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{username}}</span>
                                <img class="img-profile rounded-circle"
                                    src="{{user.profile.profile_pic.url}}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="/profil">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="/setting">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="/password">
                                    <i class="fas fa-user-lock fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Security
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-primary" href="/login">Login</a>
                        </li>

                        {% endif %}

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
               {% block content %}
               {% endblock %}
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white" style="padding: 1rem !important;">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Made by <b>PBP F-06</b></span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-danger" href="/logout">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js'></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/doughnut.js' %}"></script>
    <script src="{% static 'js/area.js' %}"></script>
    <script src="{% static 'js/navbar.js' %}"></script>
    <script src="{% static 'js/change-password.js' %}"></script>
    <script src="{% static 'js/profile-picture.js' %}"></script>
    <script src="{% static 'js/delete-user.js' %}"></script>
    <script src="{% static 'js/rumahsakit.js' %}"></script>

    <!-- forum scripts -->
  <script src="{% static 'js/crud.js' %}"></script>
  <script src="{% static 'js/ajax.js' %}"></script>
</body>

</html>

app/templates/berita.html
{% extends "base_site.html" %}
{% load static %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid" style="height: 80vh; display: flex; align-items: center; justify-content: center;">

    <!-- 404 Error Text -->
    <div class="text-center">
        <div class="error mx-auto" data-text="404">404</div>
        <p class="lead text-gray-800 mb-5">Halaman Tidak Ditemukan</p>
        <p class="text-gray-500 mb-0"></p>
        <a href="/">&larr; Kembali ke Dashboard</a>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock %}

app/templates/change_password.html
{% extends "base_site.html" %}
{% load static %}

{% block content %}
<div class="container-fluid" style="padding-bottom: 2%; display: flex; align-items: center; justify-content: center;"></div>

<div class="container mt-10 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-7">
            <div class="new_card p-3 py-5">
                <div class="d-flex justify-content-center mt-1 mb-3">
                    <h4 class="text-center">Change Your Password</h4>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {% if msz %}
                        <div class="alert {{col}}">{{msz}}</div>
                    {% endif %}
                    <div class="row mt-4 d-flex justify-content-center">
                        <div class="col-md-7">
                            <label class="labels">Current Password</label>
                            <input type="password" class="form-control" name="cpwd" required>
                        </div>
                    </div>
                    <div class="row mt-3 d-flex justify-content-center">
                        <div class="col-md-7">
                            <label class="labels">New Password</label>
                            <input type="password" class="form-control" name="npwd" id="pas" required onkeyup="check_pass()">
                        </div>
                    </div>
                    <div class="row mt-3 d-flex justify-content-center">
                        <div class="col-md-7">
                            <label class="labels">Confirm New Password</label>
                            <input type="password" class="form-control" id="cpas" required onkeyup="check_pass()">
                        </div>
                    </div>
                    <div class="mt-5 text-center buttons">
                        <button class="btn px-4" type="submit" value="Change Password" id="sbbtn">Change Password</button>
                    </div>
                </form>
                <div class="mt-4 text-center buttons">
                    <form method="get" action="/">
                        <button class="btn px-4" type="submit" value="Cancel">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/profil.html
{% extends "base_site.html" %}
{% load static %}

{% block content %}
<div class="container-fluid" style="height: 82vh; padding-bottom: 4%; display: flex; align-items: center; justify-content: center;">

    <div class="container mt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-7">
                <div class="new_card p-3 py-4">
                    <div class="text-center">
                        <img src="{{user.profile.profile_pic.url}}" width="100" height="100" class="img-profile rounded-circle">
                    </div>
                        <div class="text-center mt-4"> 
                            <div class="province" style="font-size: 13px;">
                                <span class="bg-secondary p-1 px-2 rounded text-white">{{user.profile.province}}</span>
                            </div>
                            <h4 class="mt-3 mb-0">{{user.profile.first_name}} {{user.profile.last_name}}</h4>
                            <span>+62-{{user.profile.number_phone}}</span>
                        <div class="text-center mt-2 mb-2">
                            <p class="bio" style="font-size: 11px;">{{user.profile.bio}}. </p>
                        </div>
                    <div class="buttons"> 
                        <form method="get" action="/setting">
                            <button class="btn px-4" href="/setting">Edit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/rumah_sakit.html
{% extends "base_site.html" %}
{% load static %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid" style="min-height: 80vh; display: flex; align-items: center; flex-direction: column;">

    <h3>Daftar Rumah Sakit</h3>
    
    <h6>Pilih Provinsi</h6>
    <form>
        <div class="select d-flex flex-column align-items-center">
            <select name="format" id="format">
                <option selected disabled>PILIH</option>
            </select>
            <br>
            <div class="mt-2">
                <input type="button" onclick="getCity()" value="Cari">
            </div>
        </div>
    </form>

    <h6>Pilih Kota/Kabupaten</h6>
    <form>
        <div class="select d-flex flex-column align-items-center">
            <select name="format2" id="format2">
                <option selected disabled>PILIH</option>
            </select>
            <br>
            <div class="mt-2">
                <input type="button" onclick="getHospital()" value="Cari">
            </div>
        </div>
    </form>

    <div id='div' class="container d-flex flex-wrap">

    </div>

    <style>
        h3 {
            color:#5f5b5b;
            height: 70px;
            margin-top: 1%;
        }
        h6 {
            color:#5f5b5b;
        }
        .card {
            margin: 0 auto;
            float: none;
            margin-bottom: 10px;
            margin-top: 30px;
        }
        .select {
            margin-bottom: 30px;
            margin-top: 5px;
        }
    </style>

</div>
<!-- /.container-fluid -->
{% endblock %}

app/templates/settings.html
{% extends "base_site.html" %}
{% load static %}

{% block content %}
<div class="container-fluid" style="padding-top: 2%; display: flex; align-items: center; justify-content: center;"></div>

<div class="container mt-10 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-8">
            <div class="new_card p-3 py-5">
                <div class="d-flex justify-content-center mb-3">
                    <h4 class="text-center">Profile Settings</h4>
                </div>
                <form action="" method="POST" class="form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if msz %}
                        <div class="alert {{col}}">{{msz}}</div>
                    {% endif %}
                    <div class="row mt-3 d-flex justify-content-center">
                        <div class="card-block">
                            <div class="picture-container">
                                <div class="picture">
                                    <img src="{{user.profile.profile_pic.url}}" width="100" height="100" class="rounded-circle" id="wizardPicturePreview"> 
                                    <input type="file" id="wizard-picture" name="profile_pic">
                                </div>
                                <label class="labels mt-2">Choose Picture</label>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-4 d-flex justify-content-center">
                        <div class="col-md-5">
                            <label class="labels">Nama Depan</label>
                            <input type="text" value="{{user.profile.first_name}}" name= "first_name" class="form-control" placeholder="First Name" maxLength ="30" id="id_first_name" required>
                        </div>
                        <div class="col-md-5">
                            <label class="labels">Nama Belakang</label>
                            <input type="text" value="{{user.profile.last_name}}" name= "last_name" class="form-control" placeholder="Last Name" maxLength ="30" id="id_last_name" required>
                        </div>
                    </div>
                    <div class="row mt-3 d-flex justify-content-center">
                        <div class="col-md-5">
                            <label class="labels">Username</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                  <div class="input-group-text">@</div>
                                </div>
                                <input type="text" value="{{request.user.username}}" name= "username" class="form-control" placeholder="Username" maxLength ="30" id="id_username" required>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <label class="labels">Email</label>
                            <input type="text" name="email" value="{{request.user.email}}" class="form-control" readonly>
                        </div>
                    </div>
                    <div class="row mt-3 d-flex justify-content-center">
                        <div class="col-md-5">
                            <label class="labels">Jenis Kelamin</label>
                            <select name="gender" value="" id="id_gender" class="form-control" required>
                                <option disable hidden selected>--Pilih Jenis Kelamin--</option>
                                <option>Laki-laki</option>
                                <option>Perempuan</option>
                            </select>
                        </div>
                        <div class="col-md-5">
                            <label class="labels">Tanggal Lahir</label>
                            <input type="date" value="{{user.profile.date_of_birth}}" name= "date_of_birth" class="form-control" placeholder="Date Of Birth" id="id_date_of_birth" required>
                        </div>
                    </div>
                    <div class="row mt-3 d-flex justify-content-center">
                        <div class="col-md-5">
                            <label class="labels">Provinsi</label>
                            <select name="province" value="{{user.profile.province}}" id="id_province" class="form-control" onchange="getSelectValue();" required>
                                <option disable hidden selected>--Pilih Provinsi--</option>
                                {% for data in response.provinsi %}
                                    <option value="{{data.nama}}">{{data.nama}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-5">
                            <label class="labels">No Telp.</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                  <div class="input-group-text"><img src="{% static 'img/indonesia.png' %}" width="20" height="15"> +62</div>
                                </div>
                                <input type="tel" value="{{user.profile.number_phone}}" name= "number_phone" class="form-control" placeholder="812-3456-789" maxLength ="12" id="id_number_phone" required>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-3 d-flex justify-content-center">
                        <div class="col-md-10">
                            <label class="labels">Bio</label>
                            <textarea class="form-control" name="bio" type="text" placeholder="Bio" required>{{user.profile.bio}}</textarea>
                        </div>
                    </div>
                    <div class="mt-5 text-center buttons">
                        <button class="btn px-4" type="submit" value="Update">Save Profile</button>
                    </div>
                </form>
                <div class="card-block">
                    <div class="mt-4 mb-5 text-center buttons">
                        <form method="get" action="/">
                            <button class="btn px-4" type="submit" value="Cancel">Cancel</button>
                        </form>
                    </div>
                </div>
                <div class="row d-flex justify-content-center">
                    <div class="col-md-5">
                        <div class="mt-4 text-center"><b>Deactivate your account</b></div>
                        <div class="mt-3 text-center deactivate">
                            <button class="btn px-4" data-toggle="modal" data-target="#deleteModal">Deactivate</button>
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Hapus akun?</h5>
                                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <div class="modal-body">Pilih "Delete" jika anda ingin menghapus akun ini.</div>
                            <div class="modal-footer">
                                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                                <a class="btn btn-danger" href="/delete-user">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}